import { EnemyKind, type LevelData, PickupKind } from './types';

export const LEVELS: LevelData[] = [
  {
    name: 'Prototype Meadow',
    platforms: [
      { x: 0, y: 0, w: 64, h: 1 },
      { x: 6, y: 1.8, w: 4, h: 1 },
      { x: 12, y: 3.2, w: 5, h: 1 },
      { x: 19, y: 4.8, w: 4, h: 1 },
      { x: 27, y: 2.3, w: 5, h: 1 },
      { x: 32, y: 4, w: 4, h: 1 },
      { x: 42, y: 2.8, w: 5, h: 1 },
      { x: 52, y: 1.8, w: 6, h: 1 },
    ],
    enemies: [
      {
        kind: EnemyKind.SleeperPlatform,
        x: 14,
        y: 4.5,
        patrol: { xMin: 12, xMax: 20 },
      },
      {
        kind: EnemyKind.BounceCritter,
        x: 28,
        y: 3.5,
        bob: { amp: 1, freq: 1.2 },
      },
      {
        kind: EnemyKind.GrumbleRock,
        x: 36,
        y: 5,
        patrol: { xMin: 34, xMax: 40 },
        lift: { height: 2.5, duration: 5 },
      },
      {
        kind: EnemyKind.PuffyPuffer,
        x: 48,
        y: 4.5,
        patrol: { xMin: 46, xMax: 52 },
      },
    ],
    notes: [
      { x: 5.5, y: 2.6 },
      { x: 8, y: 4.1 },
      { x: 21, y: 7.2 },
      { x: 34, y: 6.8 },
      { x: 54, y: 4.2 },
    ],
    pickups: [
      { kind: PickupKind.Health, x: 24, y: 3.3 },
      { kind: PickupKind.GoldenMelodyShard, x: 40, y: 7 },
    ],
    checkpoint: { x: 32, y: 1 },
    gate: { x: 60, y: 1, w: 2, h: 4 },
    noteGoal: 5,
  },
  {
    name: 'Dreamy Cliffs',
    platforms: [
      { x: 0, y: 0, w: 78, h: 1 },
      { x: 8, y: 2.4, w: 4, h: 1 },
      { x: 15, y: 5, w: 4, h: 1 },
      { x: 22, y: 7.2, w: 5, h: 1 },
      { x: 30, y: 5.4, w: 6, h: 1 },
      { x: 39, y: 3.6, w: 5, h: 1 },
      { x: 47, y: 5.4, w: 5, h: 1 },
      { x: 55, y: 2.6, w: 6, h: 1 },
    ],
    enemies: [
      {
        kind: EnemyKind.SleeperPlatform,
        x: 10,
        y: 4,
        patrol: { xMin: 8, xMax: 13 },
      },
      {
        kind: EnemyKind.BounceCritter,
        x: 18,
        y: 6.5,
        bob: { amp: 1.2, freq: 0.9 },
      },
      {
        kind: EnemyKind.DrowsySnail,
        x: 28,
        y: 7.2,
        patrol: { xMin: 27, xMax: 35 },
        sleepPulsesRequired: 2,
      },
      {
        kind: EnemyKind.PuffyPuffer,
        x: 42,
        y: 5.5,
        patrol: { xMin: 40, xMax: 46 },
      },
      {
        kind: EnemyKind.GrumbleRock,
        x: 57,
        y: 4,
        patrol: { xMin: 55, xMax: 61 },
        lift: { height: 3, duration: 6 },
      },
    ],
    notes: [
      { x: 4, y: 2.6 },
      { x: 10, y: 5.2 },
      { x: 24.5, y: 10.2 },
      { x: 41.5, y: 6.2 },
      { x: 49.5, y: 8.8 },
      { x: 70, y: 2.6 },
    ],
    pickups: [
      { kind: PickupKind.Health, x: 37, y: 5.2 },
      { kind: PickupKind.GoldenMelodyShard, x: 25, y: 11 },
      { kind: PickupKind.Health, x: 70, y: 1.5 },
    ],
    checkpoint: { x: 40, y: 1 },
    gate: { x: 76, y: 1, w: 2, h: 4 },
    noteGoal: 6,
  },
  {
    name: 'Moonlit Arena',
    platforms: [
      { x: 0, y: 0, w: 64, h: 1 },
      { x: 12, y: 1.8, w: 4, h: 0.8 },
      { x: 38, y: 1.8, w: 4, h: 0.8 },
      { x: 24, y: 3.6, w: 12, h: 0.8 },
    ],
    enemies: [
      {
        kind: EnemyKind.Boss,
        x: 20,
        y: 1,
        patrol: { xMin: 16, xMax: 32 },
        health: 4,
      },
      {
        kind: EnemyKind.BounceCritter,
        x: 16,
        y: 3.5,
        bob: { amp: 0.8, freq: 1.1 },
      },
      {
        kind: EnemyKind.BounceCritter,
        x: 41,
        y: 3.5,
        bob: { amp: 0.8, freq: 1.1 },
      },
    ],
    notes: [
      { x: 13.5, y: 4.1 },
      { x: 30, y: 6.2 },
      { x: 47.5, y: 3.6 },
    ],
    pickups: [
      { kind: PickupKind.Health, x: 15, y: 1.5 },
      { kind: PickupKind.GoldenMelodyShard, x: 30, y: 7 },
      { kind: PickupKind.Health, x: 45, y: 1.5 },
    ],
    checkpoint: { x: 10, y: 1 },
    gate: { x: 58, y: 1, w: 2, h: 4 },
    noteGoal: 3,
  },
];
